package javaNotes;

public class INTERFACE {
	
	//		INTERFACE
	//IT IS AN INTERMEDIATE BETWEEN SERVICE AND CUSTOMER.
	
	//IT IS ALSO CALLED CODING CONTRACT OR RULES REPOSITORY.
	
	//IT IS ALSO CALLED 100% ABSRACT CLASS.
	
	//THE INTERFACE I DECLARED BY USING INTERFACE KEYWORD.
	
	//ALL THE METHOD ARE BY DEFAULT PUBLIC AND ABSTRACT.
	
	//IT CANNOT HAVE INITIALIZERS AND CONSTRUCTOR.
	
	//BY INTERFACE WE CAN ACHIEVE MULTIPLE INHERIANCE WE CAN DECLARE A STATIC METHODS IS AND INTERFACE BUT, IT MUST
	//BE CALLED WITH THE HELP OF INTERFACE NAME.
	
	//ALL THE VARIABLES IN AN INTERFACE IS BY DEFAULT STATICAMD FINAL.
	
	//THE CHIL CLASS MUST IMPELMENT AS INTERFACE WHERE ASA A CHILD CLASS CANNOT EXTENDS AN INTERFACE.
	
	//WE CAN INSTANTIATE THE INTERFACE.
	//WE CAN KEEP THE INTERFACE AS A REFERENCE.

}
